- name: Install sqlite3 and libqt5pas1
  become: true
  ansible.builtin.apt:
    name:
      - sqlite3
      - libqt5pas1
    state: present
    update_cache: true

- name: Get flexpacket latest release info from GitHub
  ansible.builtin.uri:
    url: "https://api.github.com/repos/andreaspeters/flexpacket/releases/latest"
    return_content: true
    status_code: 200
    body_format: json
    method: GET
  register: release_response

- name: Install flexpacket AppImage
  become: true
  # FIXME: check for debian/ubuntu
  ansible.builtin.get_url:
    url: "https://github.com/andreaspeters/flexpacket/releases/download/{{ release_response.json.tag_name }}/flexpacket_debian13_amd64"
    dest: "/usr/local/bin/flexpacket"
    mode: 'u+rwx,g+rx,o+rx'
