# SPDX-License-Identifier: MIT-0
---
- name: Get latest release info from GitHub
  ansible.builtin.uri:
    url: "https://api.github.com/repos/andreaspeters/flexpacket/releases/latest"
    return_content: true
    status_code: 200
    body_format: json
    method: GET
  register: release_response

- name: Download AppImage
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/andreaspeters/flexpacket/releases/download/{{ release_response.json.tag_name }}/FlexPacket-x86_64.AppImage"
    dest: "/usr/local/bin/flexpacket"
    mode: 'u+rwx,g+rx,o+rx'

- name: Install sqlite3 and libqt6pas6
  become: true
  ansible.builtin.apt:
    name:
      - sqlite3
      - libqt6pas6
    state: present
    update_cache: true

- name: Create axports file
  become: true
  ansible.builtin.template:
    src: axports.j2
    dest: /etc/ax25/axports
    mode: '0644'
- name: Include packages.yml
  ansible.builtin.include_tasks: packages.yml

- name: Include pat.yml
  ansible.builtin.include_tasks: pat.yml

- name: Include go.yml
  ansible.builtin.include_tasks: go.yml

- name: Include yaac.yml
  ansible.builtin.include_tasks: yaac.yml
