# SPDX-License-Identifier: MIT-0
---
- name: Include packages.yml
  ansible.builtin.include_tasks: packages.yml

- name: Include pat.yml
  ansible.builtin.include_tasks: pat.yml

- name: Include go.yml
  ansible.builtin.include_tasks: go.yml

# - name: Include yaac.yml
#   ansible.builtin.include_tasks: yaac.yml

- name: Include ax25.yml
  ansible.builtin.include_tasks: ax25.yml

# only a x86_64 build is available
- name: Include flexpacket.yml
  ansible.builtin.include_tasks: flexpacket.yml
  when: ansible_architecture == "x86_64"

- name: Include sdrpp.yml
  ansible.builtin.include_tasks: sdrpp.yml
