# SPDX-License-Identifier: MIT-0
---
- name: Install sqlite3 and libqt6pas6
  become: true
  ansible.builtin.apt:
    name:
      - sqlite3
      - libqt6pas6
    state: present
    update_cache: true

- name: Include packages.yml
  ansible.builtin.include_tasks: packages.yml

- name: Include pat.yml
  ansible.builtin.include_tasks: pat.yml

- name: Include go.yml
  ansible.builtin.include_tasks: go.yml

- name: Include yaac.yml
  ansible.builtin.include_tasks: yaac.yml

- name: Include vial.yml
  ansible.builtin.include_tasks: vial.yml
  when: ansible_architecture == "x86_64"

- name: Include ax25.yml
  ansible.builtin.include_tasks: ax25.yml

- name: Include flexpacket.yml
  ansible.builtin.include_tasks: flexpacket.yml
  when: ansible_architecture == "x86_64"
