---
- name: Install ham packages
  become: true
  ansible.builtin.apt:
    name:
      - wsjtx-data
      - wsjtx
      - js8call
      - fldigi
      - flrig
      - flmsg
      - gpsd-tools
      - gpsd-clients
      - wwl
      - yad
    state: present
    update_cache: true
